### ISSUE TITLE
Friction reduction method to come up slopes causes moving on top of a rigid body frictionless

### ISSUE THREAD

**Issue by Crystalwarrior** [FreeFlyFall/RigidBodyController#1]
When I comment out move.gd lines 127-137, then when I am on top of a RigidBody, moving on top of it does not cause me to slide on it like on ice. However, this does break walking up slopes when I do so.

I am unsure of an elegant solution, but it somehow needs to determine that you are NOT on a slope, and the friction reduction would not be applied unless your contact points actually match the angle needed to determine it as a slope. I am unsure why this works just fine when you're standing on normal ground, but rigidbodies suddenly break this behavior.

Proposed solution:
Make sure if the contact point normal's y value is not only above a certain threshold, but it's also below one as well:
```gdscript
133				var y = state.get_contact_local_normal(i).y
134				if y > 0.1 and y < 0.8:
```

However, this needs more looking into, as it might cause bugs with pushing rigidbodies and getting stuck when doing so for whatever reason. This might be more related to the mass of the object you're trying to push, but pushing behavior might be a separate issue.
Doing this fixes it:

```gdscript
133				var y = state.get_contact_local_normal(i).y
134				if (y > 0.1 and y < 0.8) or y == 1:
```

**Comment by FreeFlyFall** [comment]
Thanks for bringing it up. I had wondered what might be causing this issue since it also happens on small static bodies. Apparently my code wasn't working the way I thought it was because you can have several contact points even with convex shapes. I'm not sure how the physics engine works. I was using the normal detection to prevent sticking to walls, but that could cause issues when pushing rigidbodies which contact you in a way that creates a negative normal. 

After thinking about it, the friction code was a bit hard to read. To make it more simple and natural, I tried just reducing the friction of the player when they're moving or not grounded. It seems to work fine for now after increasing the player mass and forces on the player. The the larger forces and inertia seem to overcome friction more easily so they don't stick to walls.

Removing the normal check brings back the issue I was using them to fix; if the player is moving against a wall that is perfectly aligned with one of the horizontal axes, they may lose all friction and still be able to add a force, causing them to go flying. It sometimes seemed to happen randomly even without the wall if moving perfectly along the axis. I can't tell whether it's a bug in the physics engine or my code, though it seems the physics engine wasn't reporting some things correctly in debugging, and I've spent too long debugging it, so I'll leave it.

On the bright side, the friction on rigidbodies should work now.
