### ISSUE TITLE
[BUG] Spamming the crouch button makes the character move backwards very fast!

### ISSUE THREAD

**Issue by GadyZ** [FreeFlyFall/RigidBodyController#4]
How to replicate: Get the controller working, quickly press the crouch key.
Kind of reminds me of bhopping in half life 2 speedruns. 
EDIT: Not only that, but if one jumps or does it too quickly one can just fly as well!

**Comment by FreeFlyFall** [comment]
This is comical. Thanks for noting. Is there a chance you changed the mass of the player? The project is still under development - e.g. I still haven't implemented sprinting quite yet, so playing around with some of the exposed values might cause different effects and I haven't tested all edge cases. I added a (supposedly) small force as the player hits the bottom of crouching because if I don't, the camera bobs up and down upon hitting the bottom. I believe from my previous debugging that the player capsule is actually bouncing for some reason after being scaled. Perhaps it's a physics engine bug that will be fixed in 4.0 sometime since the devs have mentioned physics engine updates. I should have been scaling the force based on mass so it was consistent. Let me know if you're still experiencing this after pulling the latest changes.
